#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

#screen reso
sh $HOME/.screenlayout/pc.sh
#boot compton or picom if it exists
if [ -x "$(command -v picom)" ]; then
  killall picom
  picom --shadow-exclude argb -b -f
fi
if [ -x s"$(command -v wired)" ]; then
  wired
fi

sh $HOME/.config/polybar/launch.sh --othi

feh --bg-fill $HOME/.screenlayout/wallpapers/hor/0.jpg $HOME/.screenlayout/wallpapers/vert/0.jpg
