yes | /bin/cp -r $HOME/dotfiles/.config/* $HOME/.config
yes | /bin/cp -r $HOME/dotfiles/.vim/* $HOME/.vim
yes | /bin/cp -r $HOME/dotfiles/.zsh  $HOME/
yes | /bin/cp -r $HOME/dotfiles/.vimrc $HOME/
yes | /bin/cp -r $HOME/dotfiles/.gitconfig $HOME/
yes | /bin/cp -r $HOME/dotfiles/.tmux.conf $HOME/
yes | /bin/cp -r $HOME/dotfiles/.gitconfig $HOME/
yes | /bin/cp -r $HOME/dotfiles/.profile $HOME/
yes | /bin/cp -r $HOME/dotfiles/.zshenv $HOME/
yes | /bin/cp -r $HOME/dotfiles/.zshrc $HOME/
yes | /bin/cp -r $HOME/dotfiles/.p10k.zsh $HOME/
