#!/bin/sh
xrandr \
  --output DP-2 --mode 1920x1080 --pos 3640x420 --rotate normal \
  --output DP-0 --primary --mode 2560x1440 --pos 1080x215 --rotate normal \
  --output DP-5 --mode 1920x1080 --pos 0x0 --rotate right
