#!/bin/sh
xrandr \
  --output DP-0 --mode 1920x1080 --pos 3640x420 --rotate normal \
  --output DP-1 --off \
  --output HDMI-0 --off \
  --output DP-2 --primary --mode 2560x1440 --pos 1080x215 --rotate normal \
  --output DP-3 --off \
  --output HDMI-1 --off \
  --output DP-4 --off \
  --output DP-5 --mode 1920x1080 --pos 0x0 --rotate right
