theme = "sonokai"

[editor]
line-number = "relative"
cursorline = true
cursorcolumn = true
true-color = true
rulers = [80]
bufferline = "multiple"
color-modes = true
completion-trigger-len = 1
idle-timeout = 0

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = " "
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)
[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1


[keys.normal]
l = "move_line_up"
n = "move_line_down"
h = "move_char_left"
H = "goto_line_start"
e = "move_char_right"
E = "goto_line_end"
C-l = "jump_view_up"
C-n = "jump_view_down"
C-h = "jump_view_left"
C-e = "jump_view_right"
M = "match_brackets"

"space" = { "space" = "hover" }
